#!/bin/bash
## Install the CommandT
cd ~/.vim/bundle/Command-T/ruby/command-t

## Note: use the ruby version that is the same as :ruby puts RUBY_VERSION
## if not installed you may need to $rbenv install 2.0.0-p481
rbenv local 2.0.0-p481
rbenv rehash
ruby extconf.rb
make
