" file: ~/.vim/plugins.vim {{{
NeoBundle 'MarcWeber/vim-addon-mw-utils'

"NeoBundle 'carlosgaldino/elixir-snippets'
"NeoBundle 'elixir-lang/vim-elixir'

NeoBundle 'wincent/Command-T'
NeoBundle 'ervandew/screen'
NeoBundle 'edkolev/tmuxline.vim'
NeoBundle 'tsaleh/vim-tmux'
NeoBundle 'christoomey/vim-tmux-navigator'
NeoBundle 'kien/ctrlp.vim'
NeoBundle 'mileszs/ack.vim'
NeoBundle 'rking/ag.vim'
NeoBundle 'junegunn/seoul256.vim'
NeoBundle 'mattn/gist-vim'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'fatih/vim-go'
"NeoBundle 'matthias-guenther/hammer.vim'
"NeoBundle 'Raimondi/delimitMate'
"NeoBundle 'alvan/vim-closetag'


NeoBundle 'vim-ruby/vim-ruby'
NeoBundle 'tpope/vim-bundler'
NeoBundle 'tpope/vim-dispatch'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'tpope/vim-git'
NeoBundle 'tpope/vim-markdown'
NeoBundle 'tpope/vim-rails'
NeoBundle 'tpope/vim-rake'
NeoBundle 'tpope/vim-rbenv'
NeoBundle 'tpope/vim-repeat'
NeoBundle 'tpope/vim-surround'
NeoBundle 'tpope/vim-unimpaired'

NeoBundle 'flazz/vim-colorschemes'
NeoBundle 'bling/vim-airline'
NeoBundle 'junegunn/vim-easy-align'
NeoBundle 'tomtom/tcomment_vim'
NeoBundle 'airblade/vim-gitgutter'
NeoBundle 'ntpeters/vim-better-whitespace'

NeoBundle 'kana/vim-textobj-lastpat'
NeoBundle 'kana/vim-textobj-user'
NeoBundle 'nelstrom/vim-textobj-rubyblock'
NeoBundle 'thinca/vim-visualstar.git'
NeoBundle 'tomtom/quickfixsigns_vim'
NeoBundle 'tomtom/tlib_vim'
" }}}

"NeoBundle 'elzr/vim-json'
"NeoBundle 'evanmiller/nginx-vim-syntax'
"NeoBundle 'groenewege/vim-less'
"NeoBundle 'honza/vim-snippets'
"NeoBundle 'kchmck/vim-coffee-script'
"NeoBundle 'krisajenkins/dbext.vim'
"NeoBundle 'krisajenkins/vim-pipe'
"NeoBundle 'majutsushi/tagbar'
"NeoBundle 'mattn/emmet-vim'
"NeoBundle 'mattn/webapi-vim'
"NeoBundle 'mattonrails/vim-mix'
"NeoBundle 'nono/vim-handlebars'
"NeoBundle 'sjl/gundo.vim'
"NeoBundle 'slim-template/vim-slim'
"NeoBundle 'thoughtbot/vim-rspec'
"NeoBundle 'pangloss/vim-javascript'
"NeoBundle 'Shougo/neocomplcache.vim'
"NeoBundle 'timcharper/textile.vim'

"NeoBundle 'tpope/vim-abolish'
"NeoBundle 'tpope/vim-characterize'
"NeoBundle 'tpope/vim-commentary'
"NeoBundle 'tpope/vim-cucumber'
"NeoBundle 'tpope/vim-endwise'
"NeoBundle 'tpope/vim-eunuch'
"NeoBundle 'tpope/vim-haml'
"NeoBundle 'tpope/vim-obsession'
"NeoBundle 'tpope/vim-pathogen'
"NeoBundle 'tpope/vim-sensible'

"NeoBundle 'tsaleh/vim-matchit'
"NeoBundle 'tsaleh/vim-shoulda'
"NeoBundle 'tyru/open-browser.vim'
"NeoBundle 'vim-scripts/ZoomWin'
"NeoBundle 'vim-scripts/scratch.vim'
"NeoBundle 'vim-scripts/jQuery'
"NeoBundle 'noprompt/vim-yardoc'
"NeoBundle 'xolox/vim-notes'
"NeoBundle 'xolox/vim-misc'
"NeoBundle 'gregsexton/gitv'
"NeoBundle 'leafo/moonscript-vim'
"NeoBundle 'fsouza/go.vim'
"NeoBundle 'ngmy/vim-rubocop'
"NeoBundle 'ludovicchabant/vim-lawrencium'

" Require 'nodejs' or 'v8' javascript engine to be installed!
"NeoBundle 'maksimr/vim-jsbeautify'
"NeoBundle 'toyamarinyon/vim-swift'
"NeoBundle 'lukerandall/haskellmode-vim'
"NeoBundle 'vim-scripts/ScrollColors'
" Transform markup language of choice to HTML. :help :HAMMER
" $rbenv shell system
" $sudo gem install github-markup tilt redcarpet
NeoBundleCheck
